version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run:
          name: Coverage
          command: cat /dev/null | sbt coverage

      - run:
          name: Compile test
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sbt
            - ~/.iv2/cache
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: Unit test
          command: cat /dev/null | sbt test

      - run:
          name: Running external dependencies (docker-compose)
          command: |
            docker-compose up -d
            docker ps

      - run:
          name: Integration testing
          command: cat /dev/null | sbt it:test

      - run:
          name: Coverage report
          command: cat /dev/null | sbt coverageReport

      - run:
          name: Upload report
          command: bash <(curl -s https://codecov.io/bash)
